---
- name: Install selinux policy required packages.
  yum:
    state: present
    name: "{{ item }}"
  with_items:
    - selinux-policy-targeted
    - selinux-policy

- name: Try to put SELinux in enforcing mode.
  selinux:
    policy: targeted
    state: enforcing
  when: ansible_virtualization_type != "docker"


- name: Allow SELinux booleans.
  seboolean:
    name: "{{ item }}"
    state: true
    persistent: yes
  with_items:
    - httpd_can_connect_ldap
    - httpd_can_network_connect_db
  when: ansible_virtualization_type != "docker"
